global:
  scrape_interval: 10s

scrape_configs:
  - job_name: pleiades_local
    static_configs:
    - targets:
      - host.docker.internal:9000
  - job_name: pleiades_local_2
    static_configs:
    - targets:
      - host.docker.internal:9001
