apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: kafka
  labels:
    app: pleiades
spec:
  selector:
    matchLabels:
      operated-prometheus: "true"
  endpoints:
  - port: web
