apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: kafka

---
  
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: prometheus
  namespace: kafka
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  namespace: kafka
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: kafka

---

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: kafka
  labels:
    prometheus: prometheus-pleiades
spec:
  replicas: 1
  externalUrl: http://localhost/prometheus
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      app: pleiades
  podMonitorSelector:
    matchLabels:
      app: strimzi
