name: Go Test

on:
    push:
        paths-ignore:
            - README.md
            - LICENSE.md

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                go-version: '1.14.6'
            - name: Setup Gikgo
              run: go get github.com/onsi/ginkgo/ginkgo && go get github.com/onsi/gomega/...
            - name: Configure
              run: ./configure
            - name: Run Linters
              run: make vet lint
            - name: Run Tests
              run: make test
