name: Go Test

on:
    push:
        paths-ignore:
            - README.md
            - LICENSE.md

jobs:
    tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                go-version: '1.14.6'
            - name: Setup Gikgo
              run: go get github.com/onsi/ginkgo/ginkgo && go get github.com/onsi/gomega/...
            - name: Setup Linter
              run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
            - name: Configure
              run: |
                export GOPATH=$(go env GOPATH)
                export PATH=$GOPATH/bin:$PATH
                ./configure
            - name: Run Tests
              run: make check
